final/website/modelforms/urls.py
from django.conf.urls import url

from . import views

app_name = 'modelforms'

urlpatterns = [

    # /modelforms/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # modelforms/product/entry
    url(r'^product/entry/$', views.ProductEntry.as_view(), name='product-entry'),

    # modelforms/product/2
    url(r'^product/(?P<pk>[0-9]+)/$', views.ProductUpdate.as_view(), name='product-update'),

    # modelforms/product/(?P<pk>[0-9]+)/delete
    url(r'^album/(?P<pk>[0-9]+)/delete$', views.ProductDelete.as_view(), name='product-delete'),

]

final/website/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^admin/', admin.site.urls),
    url(r'^modelforms/', include('modelforms.urls'))

]

final/website/modelforms/models.py
from django.db import models

# Create your models here.
from django.urls import reverse



class Product(models.Model):
    product_title = models.CharField(max_length=100)
    product_price = models.CharField(max_length=5)
    product_desc = models.CharField(max_length=100)

    # on submit click on the product entry page, it redirects to the url below.
    def get_absolute_url(self):
        return reverse('modelforms:index')



final/website/modelforms/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
#from django.core.urlresolvers import reverse_lazy
from django.urls import reverse_lazy

# Create your views here.
from .models import Product


# view for the index page
class IndexView(generic.ListView):
    # name of the object to be used in the index.html
    context_object_name = 'product_list'
    template_name = 'modelforms/index.html'

    def get_queryset(self):
        one_entry = Product.objects.get(id=4)
        print(one_entry.)
        print(Product.objects.all())
        return Product.objects.all()


# view for the product entry page
class ProductEntry(CreateView):
    model = Product
    # the fields mentioned below become the entry rows in the generated form
    fields = ['product_title', 'product_price', 'product_desc']


# view for the product update page
class ProductUpdate(UpdateView):
    model = Product
    # the fields mentioned below become the entyr rows in the update form
    fields = ['product_title', 'product_price', 'product_desc']


# view for deleting a product entry
class ProductDelete(DeleteView):
    model = Product
    # the delete button forwards to the url mentioned below.
    success_url = reverse_lazy('modelforms:index')

final/website/modelforms/templates/modelforms/form-template.html
{% for field in form %}
    <div class="form-group">
        <div >
            <span class="text-danger la">{{ field.errors }}</span>
        </div>
        <label  >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

final/website/modelforms/templates/modelforms/index.html
{% if product_list %}

    {% for product in product_list %}

    <ul>

    <li>
        <h2> Product-Title:{{ product.product_title }}</h2>
        <h2>Price:${{ product.product_price }}</h2>
        <h2>Description:{{ product.product_desc }} </h2>
           <form action="{% url 'modelforms:product-delete' product.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Delete</button>
        </form>
           <form action="{% url 'modelforms:product-update' product.id  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Update</button>
        </form>


    </li>


    </ul>

{% endfor %}

    {% else %}
    <h1>No product entries found on the database.</h1>


{% endif %}
     <form action="{% url 'modelforms:product-entry'  %}" method="post" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn btn-default btn-sm">Make a Product entry here</button>
        </form>

final/website/modelforms/templates/modelforms/product_form.html
 <h3>Add a New Product</h3>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'modelforms/form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>